app_config:
  redis:
    db:
      db: 1
      db_tokens: 2
      db_users: 3
      db_short_url: 4
      db_films: 5

    connection:
      host: 'localhost'
      port: 6399

    token:
      set_name: 'TOKENS_SET1'
      short_url: 'short-url1'
      film: 'films1'
